### ISSUE TITLE
Early testing and feedback

### ISSUE THREAD

**Issue by qriouslad** [ahmadawais/cPanel-EasyEngine-Migrate-CLI#1]
**Step 1:** 
Enter PATH to a publically downloadable cPanel backup [E.g. http://URL.com/backup.tar.gz]. 

Instead of URL.com, how about sitename.com?... so it is consistent with subsequent steps. Additionally, make sure that after copy-pasting to /public_html/ file permission is updated from 600 to 644, so it is downloadable.

So, change to the following?
Enter PATH to a publicly downloadable cPanel backup in your /public_html folder. Make sure file permission is set to 644. [For example: http://www.sitename.com/backup.tar.gz]. 

**Step 2:** 
Enter FOLDER name to download the backup [E.g. sitename]

Instruction is not clear enough. Will be created inside the root folder / current user's home folder? i.e. ~/sitename ?

If so, change instruction to the following?
Enter FOLDER name to download the backup [For example: sitename]. This will be created in your home directory [i.e. ~/sitename]

**Step 3:**
Enter the SITE URL for the site are migrating in this format → [E.g. siteurl.com]:

Instruction not clear enough. Is this the URL for the site in the EasyEngine server?... i.e. URL of the migration destination site? If so, change the instruction to the following?

Enter the URL for the destination site in EasyEngine → [For example: www.sitename.com or www.newsitename.com]:

**Step 4:**
Enter the DATABASE name for the db that we need to import → [E.g. site_db]:

Change to the following?
Enter the origin site's DATABASE name that we need to import. In cPanel, go to File Manager, then edit wp-config.php to check the DB name, user and password. → [For example:  sitename_db]:

**Error after downloading backup:**
Note that I'm changing the site name to newsitename.com below.

——————————————————————————————————
Backup Extracted to a folder
——————————————————————————————————
Let's create the old site with EasyEninge...
——————————————————————————————————

Only root or sudo user can run this EasyEngine

——————————————————————————————————
Copying backup files where the belong...
——————————————————————————————————
sending incremental file list
rsync: mkdir "/var/www/newsitename.com/htdocs" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(674) [Receiver=3.1.1]
——————————————————————————————————
Backup files were synced with the migrated site.
——————————————————————————————————
——————————————————————————————————
Now importing the SQL database...
——————————————————————————————————
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
——————————————————————————————————
 Do you want to search and replace something? [ y/n ]:
——————————————————————————————————
y
——————————————————————————————————
Enter what you need to SEARCH? [E.g. https://domain.com ]:
——————————————————————————————————
http://www.sitename.com
——————————————————————————————————
Enter what you need to REPLACE the search with? [E.g. http://domain.com ]:
——————————————————————————————————
http://www.newsitename.com
Error: This does not seem to be a WordPress install.
Pass --path=`path/to/wordpress` or run `wp core download`.
——————————————————————————————————
Search Replace is done.
——————————————————————————————————
——————————————————————————————————
Your migrated site is ready.
——————————————————————————————————
TIP: Edit your systems' hosts files to add the IP and check if the site you migrated is working fine or not.
——————————————————————————————————

**Additional notes** 
EasyEngine did not ask me for Database Name, Database Username, Database Password, and Database Prefix, even though I have set it up to ask for this information on each new install.

**Comment by ahmadawais** [comment]
You need to tell me the specs of your VPS OS and also this script is meant to be run by the root user. 

I will take another look at documenting the steps better.

**Comment by qriouslad** [comment]
I am on 64 bit Ubuntu 16.04. 

Indeed, I was running as a sudo user, which seems like best practice?... or, if it can only be run as root, perhaps either I missed reading it in the docs? I do see that you wrote "I recommend running CEM CLI from the root i.e. cd ~"

**Comment by ahmadawais** [comment]
Yes, currently I have only used it with the root user. But errors in your log `Only root or sudo user can run this EasyEngine` shows that you do NOT have the right permissions. I recommend to try it out as a root user and let me know.

**Comment by ahmadawais** [comment]
@qriouslad Thanks for your suggestions. I added almost all of them in the new release.

**Comment by qriouslad** [comment]
My pleasure @ahmadawais. Sorry I haven't had the time to re-test as root. Will do once I find the time. ;-)

p.s. how do I update CEM CLI on my server?

**Comment by ahmadawais** [comment]
@qriouslad Installing it again would be enough but just to be sure, uninstall it first and then reinstall it. 

``` bash
rm /usr/local/bin/cemcli
```

then run the install command.

**Comment by qriouslad** [comment]
Got it @ahmadawais. Will give it a try on my next round of testing. ;-)
